### ISSUE TITLE
想请教一下在LVIS上不使用RFS大概能到什么水平？

### ISSUE THREAD

**Issue by Monoclinic** [ModelTC/EOD#10]
看了您这边用了RFS的 APr很高…能有十几，而且和APc和APf差的不多。
我这边用YOLOX直接训LVIS，用LVIS0.5的时候甚至只有百分之1不到的mAP…我不知道是不是自己写错了…

**Comment by Monoclinic** [comment]
啊…是指APr只有零点几，整体大概10+的样子，还是比您这边低很多。

**Comment by waveboo** [comment]
Hi, thanks for your question.
I have no idea about the performance of YOLOX on the **lvisv0.5** benchmark because I haven't conducted experiments on it.
But directly applying the YOLOX series to the long-tailed situation may be inappropriate.
As claimed in [EFL](https://arxiv.org/abs/2201.02593), the YOLOX combined with our improved settings (YOLOX* series) will perform better.
For instance, the performance of YOLOX-M* (with our improved settings) on the **lvisv1.0** benchmark (without RFS, QFL loss) is 26.9/% mAP:
<img width="1198" alt="WX20220119-100857@2x" src="https://user-images.githubusercontent.com/23370986/150050280-3a8431ec-fe74-461c-8e74-961b44bac925.png">
Even without RFS, rare categories still achieve an AP of 7.5/%.
One tip is that the result is about the medium model, if you run a smaller model like the YOLOX-Small or YOLOX-Tiny, the performance will drop.

**Comment by Monoclinic** [comment]
> Hi, thanks for your question. I have no idea about the performance of YOLOX on the **lvisv0.5** benchmark because I haven't conducted experiments on it. But directly applying the YOLOX series to the long-tailed situation may be inappropriate. As claimed in [EFL](https://arxiv.org/abs/2201.02593), the YOLOX combined with our improved settings (YOLOX* series) will perform better. For instance, the performance of YOLOX-M* (with our improved settings) on the **lvisv1.0** benchmark (without RFS, QFL loss) is 26.9/% mAP: <img alt="WX20220119-100857@2x" width="1198" src="https://user-images.githubusercontent.com/23370986/150050280-3a8431ec-fe74-461c-8e74-961b44bac925.png"> Even without RFS, rare categories still achieve an AP of 7.5/%. One tip is that the result is about the medium model, if you run a smaller model like the YOLOX-Small or YOLOX-Tiny, the performance will drop.

感谢答疑。看了下您的论文，原版YOLOX+RFS+无QFL确实APr非常低，跟我这边的结果差不太多…
然后关于您刚才的这个回复，您论文中table 8写了 YOLOX*+RFS+Focal loss的情况下只有25.0的mAP，为什么这里不加Focal反而有26.9了……

**Comment by waveboo** [comment]
@Monoclinic,
Hi, the 25.0% mAP result in the table8 is trained by YOLOX-M*+RFS+FocalLoss
And the 26.9% AP result above is trained by YOLOX-M*+QualityFocalLoss (without RFS)
If the YOLOX-M*+QualityFocalLoss training with RFS, the performance will be further improved to 28.9% AP (presented in the table8 in the paper).
More details about the experimental settings in table 8 are shown in appendix A ( Combined with YOLOX) in the paper.
Please refer to it and feel free to ask any questiones, thanks.

**Comment by yqyao** [comment]
This issue is closed due to not being active. Please feel free to open it again @Monoclinic
