### ISSUE TITLE
请问如何在分类任务中使用efl loss 

### ISSUE THREAD

**Issue by baoxin1100** [ModelTC/EOD#11]
想在分类任务中使用efl loss，不清楚如何使用

**Comment by waveboo** [comment]
Hi @baoxin1100, thanks for your question.

EFL is generated from the Focal Loss. It is a sigmoid-like loss, which could theoretically be directly applied to classification tasks in a sigmoid-like way. Hence feel free to adopt the EFL to your task.
But we do not conduct any experiments on the classification tasks. For better performance, here are some tips for you when applying the EFL to the classification tasks:
1. EFL is designed for the one-stage long-tailed object detection tasks with the extreme foreground-background imbalance problem and the foreground long-tailed problem, we can not guarantee its performance in other scenarios.
2. Be careful with the gradient-guided mechanism in EFL. Since the distribution of samples of classification tasks and one-stage object detection tasks may be different, the design of the gradient-guided mechanism in EFL could be not suitable for the classification tasks, which you may need to adjust.

**Comment by baoxin1100** [comment]
> Hi @baoxin1100, thanks for your question.
> 
> EFL is generated from the Focal Loss. It is a sigmoid-like loss, which could theoretically be directly applied to classification tasks in a sigmoid-like way. Hence feel free to adopt the EFL to your task. But we do not conduct any experiments on the classification tasks. For better performance, here are some tips for you when applying the EFL to the classification tasks:
> 
> 1. EFL is designed for the one-stage long-tailed object detection tasks with the extreme foreground-background imbalance problem and the foreground long-tailed problem, we can not guarantee its performance in other scenarios.
> 2. Be careful with the gradient-guided mechanism in EFL. Since the distribution of samples of classification tasks and one-stage object detection tasks may be different, the design of the gradient-guided mechanism in EFL could be not suitable for the classification tasks, which you may need to adjust.

thanks for your answer！

**Comment by xc-chengdu** [comment]
> 



> 想在分类任务中使用efl loss，不清楚如何使用

你好，我也想这么做，可以加个联系方式交流一下吗？qq:2730006372

**Comment by Dream-High** [comment]
> 想在分类任务中使用efl loss，不清楚如何使用

你实现了在分类任务中应用EFL吗？可以请教一下吗

**Comment by Prot-debug** [comment]
> > 想在分类任务中使用efl loss，不清楚如何使用
> 
> 你实现了在分类任务中应用EFL吗？可以请教一下吗

@Dream-High 请问你把EFL用在分类中了吗？我也想请教一下【拒绝套娃，真心求问
